### ISSUE TITLE
won't generate from DB

### ISSUE THREAD

**Issue by mmickelson** [appzcoder/crud-generator#62]
I've tried a lot of things to get it to work, but I can't get it to use the tables in the database as the reference for what fields to make. Maybe I'm understanding the purpose wrong but what I'm intending to do is generate the views and controller to modify the DB. I've already created the migrations, models and the DB so I was hoping to quickly generate the CRUD forms. Is there more documentation somewhere?
What I'm getting when I use "php artisan crud:generate Product" is a page that doesn't have any fields when I click to add a product. It also generates a duplicate migration. Can you help me get this working correctly?

**Comment by azooziidev** [comment]
I think you have to specify the fields  in the command line you want manually, this tool doesn't pick them up from the model automagically:  _--fields="title:string, body:text"._
_
Also, if you have already created the models & migrations, then use the individual commands to generate controllers and views:

**Views:**
_php artisan crud:view posts --fields="title:string, body:text" --view-path="directory" --route-group=admin_

**Controllers:**
_php artisan crud:controller XXXXController --crud-name=xxxx --model-name=xxx --view-path="directory" --route-group=admin_

**Note:** You will also need to add the routes yourself in the routes.php file yourself if you use the individual crud:controller & crud:view commands rather than the crud:generate option, which does everything (models, routes, controllers, migrations, controllers) at once.

**Comment by mmickelson** [comment]
I see, that answers my question, thanks!
